name: CMake on multiple platforms
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    uses: ./.github/workflows/vcpkg_cmake_build.yml
    with:
      cmake_build_type: RelWithDebInfo
      enable_assets_pipeline: false
      fail-fast: false
