name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: Linux-x86_64.tar.gz
          - os: windows-latest
            artifact_name: Windows-x86_64.zip
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y libfreetype6-dev libglew-dev libglm-dev libsdl2-dev libsdl2-mixer-dev libtiff-dev libgl1-mesa-dev
    - name: Setup vcpkg (Windows)
      if: matrix.os == 'windows-latest'
      id: vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 'f6735d5aa1537081e8d425372ea7e585b0ad65e8'
    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}
        ${{ matrix.os == 'windows-latest' && format('-DCMAKE_TOOLCHAIN_FILE={0}/scripts/buildsystems/vcpkg.cmake', steps.vcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT) || '' }}
    - name: Build
      run: cmake --build build --config Release
    - name: Package (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir release
        cp build/opengl_app release/
        cp -r assets release/
        tar -czf Linux-x86_64.tar.gz -C release .
    - name: Package (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        mkdir release
        cp build/Release/opengl_app.exe release/
        cp -r assets release/
        Compress-Archive -Path release/* -DestinationPath Windows-x86_64.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_name }}
  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "Linux-x86_64.tar.gz/Linux-x86_64.tar.gz,Windows-x86_64.zip/Windows-x86_kg64.zip"
        tag: v${{ github.event.inputs.version }}
